name = "lean-math-puzzles"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["main"]

[leanOptions]
pp.unicode.fun = true 

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.25.1"

[[require]]
name = "verso"
git = "https://github.com/leanprover/verso"
rev = "v4.25.1"

[[lean_lib]]
name = "LeanMathPuzzles"

[[lean_exe]]
name = "main"
root = "LeanMathPuzzlesMain"
